### ISSUE TITLE
ALU @Jpnock

### ISSUE THREAD

**Issue by Jpnock** [Jpnock/verilog-cpu#8]
# Tasks

- [x] Implement an ALU which implements the all instructions from the MIPS I ISA (except DIV and DIVU)
- [x] Implement DIV and DIVU instructions which require multiple cycles
- [x] Conditional branches will most likely be evaluated by the ALU, so look into how we can integrate this
